global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'tetracrypt_backend'
    static_configs:
      - targets: ['tetracrypt-pqc-backend:5000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'tetracrypt_frontend'
    static_configs:
      - targets: ['tetracrypt-web3-frontend:3000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'starknet_node'
    static_configs:
      - targets: ['tetracrypt-starknet:5050']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'ai_security'
    static_configs:
      - targets: ['tetracrypt-ai-security:5100']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 